[package]
name = "days10_OpenGL"
version = "0.1.0"
authors = ["Amit Pandey <amit.paney2103@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
version = "0.13"
features = ["vulkan"]

